Initial QTMA
vatnz-dev/sops pull request #118
Opened 2024-06-04 22:11 UTC by motionaviation

2024-11-09 08:53 UTC, rb-vatnz requested changes

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +| Approach -> Tower   | Once established on approach, or within QN TWR's CTR/C.                  | QTMA may hold onto aircraft till `A050` with reference to [Arrivals](#retaining-aircraft-on-the-appr
```suggestion
| Approach -> Tower   | Once established on approach, or within QN TWR's CTR/C.                  | QTMA may hold onto aircraft till `A050` with reference to [Arrivals](#retaining-aircraft-on-the-approach).       |

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +| Approach -> Tower   | Once established on approach, or within QN TWR's CTR/C.                  | QTMA may hold onto aircraft till `A050` with reference to [Arrivals](#retaining-aircraft-on-the-appr
(Last `|` to be lined up - not 100% sure my suggestion does that or not)

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +Typically aircraft are given track shortening instructions as they climb through `A080` to track direct to a waypoint upon passing `A100`. Typically `TIMJO` and `SAVLA` for domestic flights and bound
```suggestion
Typically aircraft are given track shortening instructions as they climb through `A080` to track direct to a waypoint upon passing `A100`. This waypoint is typically `TIMJO` and `SAVLA` for domestic flights, and boundary fixes for Oceanic bound aircraft. This shall be coordinated with STH. 
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +Aircraft shall be issued either the `RNP Y (AR)` or `RNP Z (AR)` approaches. If a non-standard approach is requested, such as the `RNP F/G/H` or `VOR DME`, coordination shall occur. This requires agr
```suggestion
Aircraft shall be issued either the `RNP Y (AR)` or `RNP Z (AR)` approaches. If a non-standard approach is requested, such as the `RNP F/G/H` or `VOR DME`, coordination shall occur with agreement required between QTWR and QTMA. 
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +Once in QTMA airspace arrivals may be descend to `FL150` and then `A100` to commence the approach. QTMA may clear aircraft straight down to `A100` where traffic permits.
```suggestion
Once in QTMA airspace, arrivals may be descended to `FL150` and then `A100` to commence the approach. QTMA may clear aircraft straight down to `A100` where traffic permits.
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +    Due to high mountainous terrain controllers shall avoid track shorten aircraft on the STAR. But may do so where needed for seperation with other traffic.
```suggestion
    Due to high mountainous terrain, controllers shall avoid track shortening aircraft on the STAR but may do so where needed for separation with other traffic. 
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +QTMA usually elects to retain aircraft on the RNPs until they're assured separation exists at the threshold (with respect to backtracking aircraft). Down to about `A050`. This requires coordination w
```suggestion
QTMA usually elects to retain aircraft on the RNPs down to about `A050` until they are assured separation exists at the threshold (with respect to backtracking aircraft). This requires coordination with QTWR.
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +When RWY 05 is in use aircraft on the `RNP Y/Z` shall be seperated by a minimum 7 minutes at `MOPGA`, the same applies to aircraft on the `RNP F` at `LETPO`.
```suggestion
When RWY 05 is in use, aircraft on the `RNP Y/Z` shall be separated by a minimum of 7 minutes at `MOPGA`, or `LETPO` for aircraft on the `RNP F`.
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +When RWY 23 is in use aircraft on the `RNP Y/Z` shall be seperated by a minimum of 5 minutes at `ATVUP`, the same applies to aircraft on the `RNP G/H` at `GIVAK`.
```suggestion
When RWY 23 is in use, aircraft on the `RNP Y/Z` shall be separated by a minimum of 5 minutes at `ATVUP`, or `GIVAK` for aircraft on the `RNP G/H`.
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +### Time Seperation on the Approach
```suggestion
### Time Separation on the Approach
```

2024-11-09 08:53 UTC, rb-vatnz commented on docs/terminal/qtma.md
> +    Aircraft unable to reach `A092` by `SUNGU` shall be tracked further south via the missed approach track to `NV VOR` until terrain seperation can be achieved.
```suggestion
    Aircraft unable to reach `A092` by `SUNGU` shall be tracked further south via the missed approach track to `NV VOR` until terrain separation can be achieved. 
```

2024-11-10 03:45 UTC, rb-vatnz approved these changes

2024-11-11 22:28 UTC, VATNZ-MR approved these changes

2024-11-11 22:28 UTC, VATNZ-MR commented
Ready to merge - 2412

2024-11-17 21:22 UTC, merged