Intial OTMA
vatnz-dev/sops pull request #142
Opened 2024-10-24 05:58 UTC by motionaviation

2025-09-12 01:24 UTC, rb-vatnz requested changes

2025-09-12 01:24 UTC, rb-vatnz commented on docs/terminal/otma.md
> +|Transfer Flow         | Requirements                                                  | Notes                                                                       |
Line up right hand table lines to account for longer Approach->Tower entry

2025-09-12 01:24 UTC, rb-vatnz commented on docs/terminal/otma.md
> +Controllers shall note that the following STARs lead to a visual approach or the `RNP X 25` and are least preffered unless requested by the pilot: `IDLUR#A`, `LUNBA#E` and `TUTSI#E`.
```suggestion
Controllers shall note that the following STARs lead to a visual approach or the `RNP X 25` and are least preferred unless requested by the pilot: `IDLUR#A`, `LUNBA#E` and `TUTSI#E`. 
```

2025-09-12 01:24 UTC, rb-vatnz commented on docs/terminal/otma.md
> +OHA may issue STAR clearances to aircraft bound for any aerodrome within WN TMAs airspace without coordination, provided that the STAR links with the nominated runway and approach type as stated in t
This seems duplicated a bit with WTMA info later. Can you just check if the duplication is necessary?

2025-09-17 05:56 UTC, motionaviation commented on docs/terminal/otma.md
> +OHA may issue STAR clearances to aircraft bound for any aerodrome within WN TMAs airspace without coordination, provided that the STAR links with the nominated runway and approach type as stated in t
Have removed the lines from Coordination. Will leave WTMA Arrivals where it is with the info.

2025-09-20 03:22 UTC, merged