Initial Ohakea Aerodrome
vatnz-dev/sops pull request #152
Opened 2024-11-29 08:09 UTC by motionaviation

2025-02-10 23:41 UTC, VATNZ-MR requested changes

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
>  All departing aircraft require start clearance, weather VFR or IFR.
Would read better like this: `All departing VFR and IFR aircraft require start clearance`

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +| Position Name | Shortcode | Callsign | Frequency | Login ID | Usage     |
The `Callsign` Field on this table should have the RTF name, not the login ID

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +Controllers shall asign SIDs as suggested by the client. Where an aircraft requests the `OH#S` or `OH#R` departures these may be issued. An assigned heading shall be coordinated with OTMA.
Spelling - `assign`

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +All fixed wing aircraft shall be taxiied to the full length holding point at all times unless an intersection departure is requested by the pilot.
Would read better as: `All fixed wing aircraft shall be issued taxi clearance to a full length holding point, unless an intersection departure is requested by the pilot.`

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +#### Start up and Taxiing
Should be `Taxi`

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +For all circuit traffic - Jet shall fly the circuit at 1700 feet AMSL and all other aircraft shally fly the circuit at 1200 feet. Military aircraft **usually** report on base instead of downwind, how
`Military aircraft **usually** report on base instead of downwind, however a base or downwind call shall surfice for all aircraft.`

This isn't required and should be removed

2025-02-10 23:41 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +Military aircraft are required to report "gear down" before a landing clearance may be issued (this includes touch and goes etc).
Not required to be in the SOP

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +Controllers shall assign SIDs as suggested by the client. Where an aircraft requests the `OH#S` or `OH#R` departures these may be issued. An assigned heading shall be coordinated with OTMA.
```suggestion
Controllers shall assign SIDs as suggested by the client. The `OH#S` and `OH#R` departures may be issued on request from an aircraft. An assigned heading shall be coordinated with OTMA where applicable.
```

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +For all circuit traffic - Jet shall fly the circuit at 1700 feet AMSL and all other aircraft shally fly the circuit at 1200 feet.
```suggestion
For all circuit traffic - jet aircraft shall fly the circuit at `A017`, and all other aircraft shall fly the circuit at `A012`.
```

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +Miliary VFR flights arriving or departing the CTR/D shall be cleared via [Transit South, or Transit North.](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_35.1_35.2.pdf) Plain la
```suggestion
Miliary VFR flights arriving or departing the CTR/D shall be cleared via [Transit South, or Transit North.](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_35.1_35.2.pdf){ target=new } Plain language may be issued to Military VFR aircraft where needed and shall be issued to all civillian aircraft.
```

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +VFR Helicopter traffic shall be issued a [Helo Departure](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_52.3_52.4.pdf) based on their direction of flight and where they are loca
```suggestion
VFR Helicopter traffic shall be issued a [Helo Departure](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_52.3_52.4.pdf){ target=new } based on their direction of flight and where they are located on the aerodrome.
```

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +OTMA shall coordinate any non nominated approaches with TOH. Note - Military aircraft will often fly an approach for a non nominated runway, then circle to land the nominated runway.
```suggestion
OTMA shall coordinate any non-nominated approaches with TOH. Note - Military aircraft will often fly an approach for a non-nominated runway, then circle to land the nominated runway.
```

2025-02-12 01:07 UTC, jamstu26 commented on docs/aerodromes/Class-D/nzoh.md
> +TOH shall coordinate any IFR departure with OTMA for a radar release. And assigned heading where appliciable.
```suggestion
TOH shall coordinate all IFR departures with OTMA for a radar release, as well as an assigned heading where applicable.
```

2025-04-08 08:22 UTC, VATNZ-MR requested changes

2025-04-08 08:22 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +Miliary VFR flights arriving or departing the CTR/D shall be cleared via [Transit South, or Transit North.](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_35.1_35.2.pdf){ target=
Spelling

2025-04-08 08:22 UTC, mwr2410 commented on docs/aerodromes/Class-D/nzoh.md
> +  ![Ohakea areas of responsibility](./assets/nzoh-resp.png)
Can this diagram be tidied up? It's cut off in places and also not straight in others

2025-04-08 08:22 UTC, VATNZ-MR commented on docs/aerodromes/Class-D/nzoh.md
> +## Tower
Want to add anything about the approaches?

2025-04-30 07:21 UTC, VATNZ-MR submitted a review, later dismissed
Needs more meat, refer to https://www.vatnz.net/controllers/standard-operating-procedures/ohakea-tma/ and improve on what is there.

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +As default for `RWY 27/09` the ILS shall be the nominated approach. For `RWY 15/33` as there is no ILS, `RNP` shall be the nominated appraoch. For any non-nominated approaches refer to [Coordination]
```suggestion
As default for `RWY 09/27` the ILS shall be the nominated approach. For `RWY 15/33` as there is no ILS, `RNP` shall be the nominated approach. For any non-nominated approaches refer to [Coordination](#coordination)
```
Just to keep runways in same order.

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +Aircraft shall be restricted to `A030` unless otherwise coordinated with TOH.
```suggestion
Aircraft shall be restricted to `A030` unless otherwise coordinated with OTMA.
```
?

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +Military VFR flights arriving or departing the CTR/D shall be cleared via [Transit South, or Transit North.](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_35.1_35.2.pdf){ target
I guess this is a VATIMism but what about non-Military? Are we best to just make it all VFRs to go via Transit N/S?

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +overflying Sanson (R092/1.5 NM OH VOR/DME) and Bulls (R325/2NM OH VOR/DME). To meet this requirement when operating from the most critical runways the following specific procedures are to be adhered
Join this line to last one rather than wrap I think

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +  Sanson and Bulls. However, when adverse weather
Join these lines up to make one long paragraph

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +**Arrival — RWY 15 and RWY 27**
```suggestion
### Arrival — RWY 15 and RWY 27
```

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +**ATC requirement: H24 — all IFR flights cleared at 11,000 ft or above:**
Not sure if this should be some kind of header or whether this should be an information box or similar? (Unfortunately Vercel preview isn't working so can't visualise it)

2025-08-18 08:24 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +OTMA shall coordinate any non-nominated approaches with TOH. Note - Military aircraft will often fly an approach for a non-nominated runway, then circle to land the nominated runway.
Not sure we need this here - I think mostly we've gone with outbound co-ord not inbound?

2025-09-12 01:18 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +| Ohakea ADC    | TOH       | Ohakea Tower  | 134.500   | NZOH_TWR | Primary   |
Also include TMA here as we do that for other aerodromes

2025-09-17 05:34 UTC, motionaviation commented on docs/aerodromes/Class-D/nzoh.md
> +Military VFR flights arriving or departing the CTR/D shall be cleared via [Transit South, or Transit North.](https://www.aip.net.nz/assets/AIP/Aerodrome-Charts/Ohakea-NZOH/NZOH_35.1_35.2.pdf){ target
Might be the best way to do it, shall amend the wording

2025-09-17 05:55 UTC, rb-vatnz commented on docs/aerodromes/Class-D/nzoh.md
> +ATC requirement: H24 — all IFR flights cleared at 11,000 ft or above:
```suggestion
All IFR flights cleared at 11,000 ft or above:
```

2025-09-20 03:19 UTC, rb-vatnz approved these changes

2025-09-20 03:21 UTC, merged